<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AmitPC" ignored="0" name="classic" tests="5" failures="1" timestamp="07 Jan 2021 17:16:51 GMT" time="58.746" errors="0">
  <testcase name="set" time="13.857" classname="com.app.test.LoginTest_1">
    <skipped/>
  </testcase> <!-- set -->
  <testcase name="set" time="17.833" classname="com.app.test.LoginTest_1">
    <skipped/>
  </testcase> <!-- set -->
  <testcase name="set" time="12.911" classname="com.app.test.LoginTest_1">
    <skipped/>
  </testcase> <!-- set -->
  <testcase name="set" time="12.974" classname="com.app.test.LoginTest_1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.app.test.LoginTest_1.set(LoginTest_1.java:18)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- set -->
  <testcase name="clos" time="1.125" classname="com.app.test.LoginTest_1"/>
</testsuite> <!-- classic -->
